routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.home')->name('landing');
});
Route::group(['namespace'=>'\App\Http\Controllers'],function (){
    Route::get('/', 'FrontendController@homePage')->name('landing');
    Route::get('products','FrontendController@listAllProducts')->name('all-products');
    Route::get('products/{slug}','FrontendController@getProductDetail')->name('product-detail');
    Route::get('collections/{slug}','FrontendController@getCollectionDetail')->name('collection-detail');
    Route::get('pages/{slug}','FrontendController@getPageDetail')->name('page-detail');
    Route::get('blog','FrontendController@getAllBlog')->name('all-blogs');
    Route::get('blog/{slug}','FrontendController@blogDetail')->name('blog-detail');
    Route::get('page/contact-us','FrontendController@getContactUs')->name('contact');
    Route::get('search','FrontendController@searchResult')->name('search');
    Route::get('category','FrontendController@listAllProducts');
    Route::get('category/{slug}','FrontendController@getProductFromCategory')->name('cat-products');
    Route::get('category/{parent_slug}/{slug}','FrontendController@getProductFromSubCategory')->name('sub-cat-products');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=> '/admin','middleware'=> ['auth','admin'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('banner','BannerController')->except('show');
    Route::get('/banner/status-change/{id}/{status}','BannerController@changeStatus')->name('banner-change-status');
    Route::resource('category','CategoryController');
    Route::get('/category/status-change/{id}/{status}','CategoryController@changeStatus')->name('category-change-status');
    Route::resource('brand','BrandController')->except('show');
    Route::get('/brand/status-change/{id}/{status}','BrandController@changeStatus')->name('brand-change-status');
    Route::resource('product','ProductController');
    Route::get('/product/status-change/{id}/{status}','ProductController@changeStatus')->name('product-change-status');
    Route::resource('collection','ProductCollectionController');
    Route::get('/collection/status-change/{id}/{status}','ProductCollectionController@changeStatus')->name('collection-change-status');
    Route::resource('offer','OfferProductCollectionController');
    Route::get('/offer/status-change/{id}/{status}','OfferProductCollectionController@changeStatus')->name('offer-change-status');
    Route::resource('user','UserController');
    Route::get('/user/status-change/{id}/{status}','UserController@changeStatus')->name('user-change-status');
    Route::get('/user/{id}/change-password','UserController@showPasswordChangeForm')->name('change-pwd');
    Route::patch('/user/{id}/change-password','UserController@updatePassword')->name('user-update-password');
    Route::resource('page','PageController')->except(['show','store','delete']);
    Route::get('/page/status-change/{id}/{status}','PageController@changeStatus')->name('page-change-status');
    Route::resource('blog','BlogController');
    Route::get('/blog/status-change/{id}/{status}','BlogController@changeStatus')->name('blog-change-status');
});
Route::group(['prefix'=> '/customer','middleware'=> ['auth','customer'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@customer')->name('customer');

});
Route::group(['prefix'=> '/seller','middleware'=> ['auth','seller'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@seller')->name('seller');
    Route::get('/product','ProductController@getProductBySeller')->name('seller.product');
    Route::get('/product/create','ProductController@showSellerProductForm')->name('seller.product.create');
    Route::get('/product/{id}','ProductController@getProductEditForm')->name('seller.product.edit');
    Route::post('/product','ProductController@storeProduct')->name('seller.product.store');
    Route::patch('/product/{id}','ProductController@updateProduct')->name('seller.product.update');
    Route::delete('/product/{id}/destroy','ProductController@deleteProduct')->name('seller.product.destroy');
    Route::get('/collection','ProductCollectionController@getCollectionBySeller')->name('seller.collection');
    Route::get('/collection/create','ProductCollectionController@showSellerCollectionForm')->name('seller.collection.create');
    Route::get('/collection/{id}','ProductCollectionController@getCollectionEditForm')->name('seller.collection.edit');
    Route::post('/collection','ProductCollectionController@storeCollection')->name('seller.collection.store');
    Route::patch('/collection/{id}','ProductCollectionController@updateCollection')->name('seller.collection.update');
    Route::delete('/collection/{id}/destroy','ProductCollectionController@deleteCollection')->name('seller.collection.destroy');
});
Route::patch('/update-me',[App\Http\Controllers\HomeController::class,'updateMe'])->name('update-me')->middleware('auth');
Route::post('/category/sub-cat',[App\Http\Controllers\CategoryController::class,'getAllSubCats'])->name('get-sub-cats')->middleware('auth');
Route::patch('/update-password',[App\Http\Controllers\HomeController::class,'updatePassword'])->name('update-password')->middleware('auth');

resources/views/admin/page/form.blade.php
@extends('layouts.admin')
@section('title','Page Form || Ecommerce Website')
@section('main_content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Page Form </div>
                    <a href="{{ route('page.index') }}" title="List All Page" class="btn btn-info btn-sm btn-circle"><i class="fa fa-eye"></i></a>
                </div>
                <div class="ibox-body">
                        {{ Form::open(['url'=>route('page.update',$page_detail->id) ,'class'=>'form','files'=>true]) }}
                        @method('patch')
                    <div class="form-group row">
                        {{ Form::label('summary','Summary',['class'=>'col-sm-12 col-md-3 text-md-right']) }}
                        <div class="col-sm-12 col-md-9">
                            {{ Form::textarea('summary',@$page_detail->summary,['class'=>'form-control form-control-sm','id'=>'summary','required'=>true,'placeholder'=>'Enter summary for page','rows'=>3,'style'=> 'resize:none;']) }}
                            @error('summary')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('description','Description',['class'=>'col-sm-12 col-md-3 text-md-right']) }}
                        <div class="col-sm-12 col-md-9">
                            {{ Form::textarea('description',@$page_detail->description,['class'=>'form-control form-control-sm','id'=>'description','required'=>false,'placeholder'=>'Enter description for page','rows'=>3,'style'=> 'resize:none;']) }}
                            @error('summary')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('status','Status',['class'=>'col-sm-12 col-md-3 text-md-right']) }}
                        <div class="col-sm-12 col-md-9">
                            {{ Form::select('status',['active'=>"Published",'inactive'=>"Un-published"],@$page_detail->status,['class'=>'form-control form-control-sm','id'=>'status','required'=>true]) }}
                            @error('status')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('image_update','Image',['class'=>'col-sm-12 col-md-3 text-md-right']) }}
                        <div class="col-sm-12 col-md-5">
                            {{ Form::file('image',['id'=>'image_update','required'=>(isset($page_detail) ? false : true),'accept'=>"image/*",'onchange'=>"readURL(this,'thumb')"]) }}
                            @error('image')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col-md-3">
                            @if(isset($page_detail) && !empty($page_detail->image))
                                <img src="{{ asset("uploads/page/".$page_detail->image) }}" alt="" id="thumb" class="img-fluid img-thumbnail">
                            @else
                                <img src="" alt="" id="thumb" class="img-fluid img-thumbnail">
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12 col-md-9 offset-md-3">
                            <button type="submit" class="btn btn-success btn-block btn-sm" >Submit</button>
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/page/index.blade.php
@extends('layouts.admin')
@section('title','Page List || Ecommerce Website')
@section('main_content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">All Page List</div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover data-table">
                        <thead class="thead-dark">
                        <th>Title</th>
                        <th>Summary</th>
                        <th>Image</th>
                        <th>Status</th>
                        <th>Action</th>
                        </thead>
                        <tbody>
                        @if($page_list->count())
                            @foreach($page_list as $page)
                                <tr>
                                    <td>{{$page->title}}</td>
                                    <td>{{$page->summary}}</td>
                                    <td>
                                        @if($page->image != null)
                                        <a href="{{ asset('uploads/page/'.$page->image) }}" data-lightbox = "image-{{ $page->id }}" data-title = {{ $page->title }}>Preview</a>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{ route('page-change-status',[$page->id,$page->status]) }}" class="badge badge-{{ $page->status == 'active' ? 'success' : 'danger' }}">{{ $page->status == 'active' ? 'Published' : 'Un-published' }}</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('page.edit',$page->id) }}" title="Edit this page" class="btn btn-primary btn-sm btn-circle">
                                            <i class="fa fa-pen"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection