routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.home')->name('landing');
});
Route::group(['namespace'=>'\App\Http\Controllers'],function (){
    Route::get('/', 'FrontendController@homePage')->name('landing');
    Route::get('products','FrontendController@listAllProducts')->name('all-products');
    Route::get('products/{slug}','FrontendController@getProductDetail')->name('product-detail');
    Route::get('collections/{slug}','FrontendController@getCollectionDetail')->name('collection-detail');
    Route::get('pages/{slug}','FrontendController@getPageDetail')->name('page-detail');
    Route::get('blog','FrontendController@getAllBlog')->name('all-blogs');
    Route::get('blog/{slug}','FrontendController@blogDetail')->name('blog-detail');
    Route::get('page/contact-us','FrontendController@getContactUs')->name('contact');
    Route::get('search','FrontendController@searchResult')->name('search');
    Route::get('category','FrontendController@listAllProducts');
    Route::get('category/{slug}','FrontendController@getProductFromCategory')->name('cat-products');
    Route::get('category/{parent_slug}/{slug}','FrontendController@getProductFromSubCategory')->name('sub-cat-products');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=> '/admin','middleware'=> ['auth','admin'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('banner','BannerController')->except('show');
    Route::get('/banner/status-change/{id}/{status}','BannerController@changeStatus')->name('banner-change-status');
    Route::resource('category','CategoryController');
    Route::get('/category/status-change/{id}/{status}','CategoryController@changeStatus')->name('category-change-status');
    Route::resource('brand','BrandController')->except('show');
    Route::get('/brand/status-change/{id}/{status}','BrandController@changeStatus')->name('brand-change-status');
    Route::resource('product','ProductController');
    Route::get('/product/status-change/{id}/{status}','ProductController@changeStatus')->name('product-change-status');
    Route::resource('collection','ProductCollectionController');
    Route::get('/collection/status-change/{id}/{status}','ProductCollectionController@changeStatus')->name('collection-change-status');
    Route::resource('offer','OfferProductCollectionController');
    Route::get('/offer/status-change/{id}/{status}','OfferProductCollectionController@changeStatus')->name('offer-change-status');
    Route::resource('user','UserController');
    Route::get('/user/status-change/{id}/{status}','UserController@changeStatus')->name('user-change-status');
    Route::get('/user/{id}/change-password','UserController@showPasswordChangeForm')->name('change-pwd');
    Route::patch('/user/{id}/change-password','UserController@updatePassword')->name('user-update-password');
    Route::resource('page','PageController')->except(['show','store','delete']);
    Route::get('/page/status-change/{id}/{status}','PageController@changeStatus')->name('page-change-status');
    Route::resource('blog','BlogController');
    Route::get('/blog/status-change/{id}/{status}','BlogController@changeStatus')->name('blog-change-status');
});
Route::group(['prefix'=> '/customer','middleware'=> ['auth','customer'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@customer')->name('customer');

});
Route::group(['prefix'=> '/seller','middleware'=> ['auth','seller'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@seller')->name('seller');
    Route::get('/product','ProductController@getProductBySeller')->name('seller.product');
    Route::get('/product/create','ProductController@showSellerProductForm')->name('seller.product.create');
    Route::get('/product/{id}','ProductController@getProductEditForm')->name('seller.product.edit');
    Route::post('/product','ProductController@storeProduct')->name('seller.product.store');
    Route::patch('/product/{id}','ProductController@updateProduct')->name('seller.product.update');
    Route::delete('/product/{id}/destroy','ProductController@deleteProduct')->name('seller.product.destroy');
    Route::get('/collection','ProductCollectionController@getCollectionBySeller')->name('seller.collection');
    Route::get('/collection/create','ProductCollectionController@showSellerCollectionForm')->name('seller.collection.create');
    Route::get('/collection/{id}','ProductCollectionController@getCollectionEditForm')->name('seller.collection.edit');
    Route::post('/collection','ProductCollectionController@storeCollection')->name('seller.collection.store');
    Route::patch('/collection/{id}','ProductCollectionController@updateCollection')->name('seller.collection.update');
    Route::delete('/collection/{id}/destroy','ProductCollectionController@deleteCollection')->name('seller.collection.destroy');
});
Route::patch('/update-me',[App\Http\Controllers\HomeController::class,'updateMe'])->name('update-me')->middleware('auth');
Route::post('/category/sub-cat',[App\Http\Controllers\CategoryController::class,'getAllSubCats'])->name('get-sub-cats')->middleware('auth');
Route::patch('/update-password',[App\Http\Controllers\HomeController::class,'updatePassword'])->name('update-password')->middleware('auth');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;
    protected $fillable = ['title','slug','image','status','added_by'];
    public function brandRules($act = 'add'){
        $rules =  ['title' => ['required','string','max:150','min:1'],
            'image' => ['sometimes','image','max:5000'],
            'status' => ['required','in:active,inactive']
        ];
        if($act != 'add'){
            $rules['image'] = ['sometimes','image','max:5000'];
        }
        return $rules;
    }
    public function getSlug($title){
        $slug = \Str::slug($title);
        if($this->where('slug',$slug)->count()){
            $slug .= rand(0,99);
        }
        return $slug;
    }
    public function get(){
        return $this->orderBy('created_at','desc')->orderBy('id','desc')->get();
    }
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Brand;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $brand;
    public function __construct(Brand $brand)
    {
        $this->brand = $brand;
    }

    public function index()
    {
        $brand_list = $this->brand->get();
        return  view('admin.brand.index')->with('brand_list',$brand_list);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return  view('admin.brand.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate($this->brand->brandRules());
        $data = $request->except('image');
        $data['added_by'] = auth()->user()->id;
        $data['slug'] = $this->brand->getSlug($request->title);
        if($request->image){
            $image_name = imageUpload($request->image,'brand',env('BrandImageSize','500x500'));
            if($image_name){
                $data['image'] = $image_name;
            }
        }
        $this->brand->fill($data);
//        dd($this->brand);
        $status = $this->brand->save();
        if($status){
            $request->session()->flash('success','Brand successfully added.');
            return redirect()->route('brand.index');
        }else{
            $request->session()->flash('error','Sorry!, error while adding brand');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->validateId($id);

        return  view('admin.brand.form')->with('brand_detail',$this->brand);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->brand = $this->brand->find($id);
        $request->validate($this->brand->brandRules($act = 'update'));
        $data = $request->except('image');
        if($request->image){
            $image_image = imageUpload($request->image,'brand',env('BrandImageSize','1280x768'));
            if($image_image){
                $data['image'] = $image_image;
            }
            if($this->brand->image){
                deleteImage($this->brand->image,'brand');
            }
        }
        $this->brand->fill($data);
        $status = $this->brand->save();
        if($status){
            $request->session()->flash('success','Parent brand successfully updated');
            return redirect()->route('brand.index');
        }else{
            $request->session()->flash('error','Sorry!, error while updating parent brand');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->validateId($id);
        $image = $this->brand->image;
        $status = $this->brand->delete();
        if($status){
            if($image != null){
                deleteImage($image,'brand');
            }
            request()->session()->flash('success','Brand successfully deleted');
        }else{
            request()->session()->flash('error','Sorry!, Brand does not exists');
        }
        return redirect()->route('brand.index');
    }

    private function validateId($id){
        $this->brand = $this->brand->find($id);
        if(!$this->brand){
            request()->session()->flash('error','Sorry!, Brand does not exists');
            return  redirect()-route('brand.index');
        }
    }

    public function changeStatus(Request $request){
        $this->validateId($request->id);
        if($this->brand->status == 'active') {
            $this->brand->status = 'inactive';
        }else{
            $this->brand->status = 'active';
        }
        $status = $this->brand->save();
        if($status){
            $request->session()->flash('success','Brand status successfully changed ');
            return redirect()->route('brand.index');
        }else{
            $request->session()->flash('error','Sorry!, error while changing brand status');
            return redirect()->back();
        }
    }
}

resources/views/admin/brand/form.blade.php
@extends('layouts.admin')
@section('title','Brand Form || Ecommerce Website')
@section('main_content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Brand Form </div>
                    <a href="{{ route('brand.index') }}" title="List All Brand" class="btn btn-info btn-sm btn-circle"><i class="fa fa-eye"></i></a>
                </div>
                <div class="ibox-body">
                    @if(isset($brand_detail))
                        {{ Form::open(['url'=>route('brand.update',$brand_detail->id) ,'class'=>'form','files'=>true]) }}
                        @method('patch')
                    @else
                        {{ Form::open(['url'=>route('brand.store') ,'class'=>'form','files'=>true]) }}
                    @endif
                    <div class="form-group row">
                        {{ Form::label('title','Title',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                        <div class="col-sm-12 col-md-7">
                            {{ Form::text('title',@$brand_detail->title,['class'=>'form-control form-control-sm','id'=>'title','required'=>true,'placeholder'=>'Enter title for brand']) }}
                            @error('title')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('status','Status',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                        <div class="col-sm-12 col-md-7">
                            {{ Form::select('status',['active'=>"Published",'inactive'=>"Un-published"],@$brand_detail->status,['class'=>'form-control form-control-sm','id'=>'status','required'=>true]) }}
                            @error('status')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('image_update','Image',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                        <div class="col-sm-12 col-md-4">
                            {{ Form::file('image',['id'=>'image_update','required'=> false,'accept'=>"image/*",'onchange'=>"readURL(this,'thumb')"]) }}
                            @error('image')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col-md-3">
                            @if(isset($brand_detail) && !empty($brand_detail->image))
                                <img src="{{ asset("uploads/brand/".$brand_detail->image) }}" alt="" id="thumb" class="img-fluid img-thumbnail">
                            @else
                                <img src="" alt="" id="thumb" class="img-fluid img-thumbnail">
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12 col-md-7 offset-md-5">
                            <button type="submit" class="btn btn-success btn-block btn-sm" >Submit</button>
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/brand/index.blade.php
@extends('layouts.admin')
@section('title','Brand List || Ecommerce Website')
@section('main_content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">All Brand List</div>
                    <a href="{{ route('brand.create') }}" title="Add Brand" class="btn btn-success btn-circle"><i class="fa fa-plus"></i></a>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover data-table ">
                        <thead class="thead-dark">
                        {{--                            <th>S.N.</th>--}}
                        <th>Title</th>
                        <th>Summary</th>
                        <th>Image</th>
                        <th>Status</th>
                        <th>Action</th>
                        </thead>
                        <tbody>
                        @if($brand_list->count())
                            @foreach($brand_list as $brand_list)
                                <tr>
                                    {{--                                    <td>{{$brand_list->id}}</td>--}}
                                    <td>{{$brand_list->title}}</td>
                                    <td><span>{{$brand_list->summary}}</span></td>
                                    <td>
                                        <a href="{{ asset('uploads/brand/'.$brand_list->image) }}" data-lightbox = "image-{{ $brand_list->id }}" data-title = {{ $brand_list->title }}>Preview</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('brand-change-status',[$brand_list->id,$brand_list->status]) }}" class="badge badge-{{ $brand_list->status == 'active' ? 'success' : 'danger' }}">{{ $brand_list->status == 'active' ? 'Published' : 'Un-published' }}</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('brand.edit',$brand_list->id) }}" title="Edit this brand" class="btn btn-primary btn-sm btn-circle" >
                                            <i class="fa fa-pen"></i>
                                        </a>
                                        <a href="javascript:;" title="Delete this brand" class="btn btn-warning btn-sm btn-circle btn-delete">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                        {{ Form::open(['url' => route('brand.destroy',$brand_list->id) , 'class' => 'delete-form' ]) }}
                                        @method('delete')
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
<!-- Sub-brand view   Modal -->
<div class="modal fade" id="subBrandList" role="dialog">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Sub-brand list</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <table class="table table-striped table-hover data-table ">
                    <thead class="thead-dark">
                    <th>Title</th>
                    <th>Summary</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th>Action</th>
                    </thead>
                    <tbody id="sub_cat_body">
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>