routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.home')->name('landing');
});
Route::group(['namespace'=>'\App\Http\Controllers'],function (){
    Route::get('/', 'FrontendController@homePage')->name('landing');
    Route::get('products','FrontendController@listAllProducts')->name('all-products');
    Route::get('products/{slug}','FrontendController@getProductDetail')->name('product-detail');
    Route::get('collections/{slug}','FrontendController@getCollectionDetail')->name('collection-detail');
    Route::get('pages/{slug}','FrontendController@getPageDetail')->name('page-detail');
    Route::get('blog','FrontendController@getAllBlog')->name('all-blogs');
    Route::get('blog/{slug}','FrontendController@blogDetail')->name('blog-detail');
    Route::get('page/contact-us','FrontendController@getContactUs')->name('contact');
    Route::get('search','FrontendController@searchResult')->name('search');
    Route::get('category','FrontendController@listAllProducts');
    Route::get('category/{slug}','FrontendController@getProductFromCategory')->name('cat-products');
    Route::get('category/{parent_slug}/{slug}','FrontendController@getProductFromSubCategory')->name('sub-cat-products');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=> '/admin','middleware'=> ['auth','admin'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('banner','BannerController')->except('show');
    Route::get('/banner/status-change/{id}/{status}','BannerController@changeStatus')->name('banner-change-status');
    Route::resource('category','CategoryController');
    Route::get('/category/status-change/{id}/{status}','CategoryController@changeStatus')->name('category-change-status');
    Route::resource('brand','BrandController')->except('show');
    Route::get('/brand/status-change/{id}/{status}','BrandController@changeStatus')->name('brand-change-status');
    Route::resource('product','ProductController');
    Route::get('/product/status-change/{id}/{status}','ProductController@changeStatus')->name('product-change-status');
    Route::resource('collection','ProductCollectionController');
    Route::get('/collection/status-change/{id}/{status}','ProductCollectionController@changeStatus')->name('collection-change-status');
    Route::resource('offer','OfferProductCollectionController');
    Route::get('/offer/status-change/{id}/{status}','OfferProductCollectionController@changeStatus')->name('offer-change-status');
    Route::resource('user','UserController');
    Route::get('/user/status-change/{id}/{status}','UserController@changeStatus')->name('user-change-status');
    Route::get('/user/{id}/change-password','UserController@showPasswordChangeForm')->name('change-pwd');
    Route::patch('/user/{id}/change-password','UserController@updatePassword')->name('user-update-password');
    Route::resource('page','PageController')->except(['show','store','delete']);
    Route::get('/page/status-change/{id}/{status}','PageController@changeStatus')->name('page-change-status');
    Route::resource('blog','BlogController');
    Route::get('/blog/status-change/{id}/{status}','BlogController@changeStatus')->name('blog-change-status');
});
Route::group(['prefix'=> '/customer','middleware'=> ['auth','customer'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@customer')->name('customer');

});
Route::group(['prefix'=> '/seller','middleware'=> ['auth','seller'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@seller')->name('seller');
    Route::get('/product','ProductController@getProductBySeller')->name('seller.product');
    Route::get('/product/create','ProductController@showSellerProductForm')->name('seller.product.create');
    Route::get('/product/{id}','ProductController@getProductEditForm')->name('seller.product.edit');
    Route::post('/product','ProductController@storeProduct')->name('seller.product.store');
    Route::patch('/product/{id}','ProductController@updateProduct')->name('seller.product.update');
    Route::delete('/product/{id}/destroy','ProductController@deleteProduct')->name('seller.product.destroy');
    Route::get('/collection','ProductCollectionController@getCollectionBySeller')->name('seller.collection');
    Route::get('/collection/create','ProductCollectionController@showSellerCollectionForm')->name('seller.collection.create');
    Route::get('/collection/{id}','ProductCollectionController@getCollectionEditForm')->name('seller.collection.edit');
    Route::post('/collection','ProductCollectionController@storeCollection')->name('seller.collection.store');
    Route::patch('/collection/{id}','ProductCollectionController@updateCollection')->name('seller.collection.update');
    Route::delete('/collection/{id}/destroy','ProductCollectionController@deleteCollection')->name('seller.collection.destroy');
});
Route::patch('/update-me',[App\Http\Controllers\HomeController::class,'updateMe'])->name('update-me')->middleware('auth');
Route::post('/category/sub-cat',[App\Http\Controllers\CategoryController::class,'getAllSubCats'])->name('get-sub-cats')->middleware('auth');
Route::patch('/update-password',[App\Http\Controllers\HomeController::class,'updatePassword'])->name('update-password')->middleware('auth');

resources/views/admin/partials/footer.blade.php
<footer class="page-footer">
    <div class="font-13 m-auto">{{date('Y')}} © <b>Broadway CMS</b> - All rights reserved.</div>
    <div class="to-top"><i class="fa fa-angle-double-up"></i></div>
</footer>
<!-- User update  Modal -->
<div class="modal fade" id="editProfile" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Edit Profile</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
        {{ Form::open(['url'=>route('update-me') ,'class'=>'form','files'=>true]) }}
            @method('patch')
            <!-- Modal body -->
            <div class="modal-body">
               <div class="form-group row">
               {{ Form::label('name','Name',['class'=>'col-sm-12 col-md-3']) }}
                   <div class="col-sm-12 col-md-9">
                       {{ Form::text('name',auth()->user()->name,['class'=>'form-control form-control-sm','id'=>'name','required'=>true,'placeholder'=>'Enter your name']) }}
                   </div>
               </div>
                <div class="form-group row">
                    {{ Form::label('address','Address',['class'=>'col-sm-12 col-md-3']) }}
                    <div class="col-sm-12 col-md-9">
                        {{ Form::text('address',@(auth()->user()->userInfo['address']),['class'=>'form-control form-control-sm','id'=>'address','required'=>false,'placeholder'=>'Enter your address']) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('phone','Phone',['class'=>'col-sm-12 col-md-3']) }}
                    <div class="col-sm-12 col-md-9">
                        {{ Form::tel('phone',@(auth()->user()->userInfo['phone']),['class'=>'form-control form-control-sm','id'=>'phone','required'=>false,'placeholder'=>'Enter your phone number']) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('image','Image',['class'=>'col-sm-12 col-md-3']) }}
                    <div class="col-sm-12 col-md-9">
                        {{ Form::file('image',['id'=>'image','required'=>false]) }}
                    </div>
                </div>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success" >Save</button>

            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
<!-- password update   Modal -->
<div class="modal fade" id="updatePassword" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Update Password</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
        {{ Form::open(['url'=>route('update-password') ,'class'=>'form']) }}
        @method('patch')
        <!-- Modal body -->
            <div class="modal-body">
                <div class="form-group row">
                    {{ Form::label('current_password','Current Password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                    <div class="col-sm-12 col-md-7">
                        {{ Form::password('current_password',['class'=>'form-control form-control-sm','id'=>'current_password','required'=>true,'placeholder'=>'Enter your current password']) }}
                    </div>
                </div>

                <div class="form-group row">
                    {{ Form::label('password','New Password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                    <div class="col-sm-12 col-md-7">
                        {{ Form::password('password',['class'=>'form-control form-control-sm','id'=>'password','required'=>true,'placeholder'=>'Enter your new password']) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('confirmation_password','Confirmation Password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                    <div class="col-sm-12 col-md-7">
                        {{ Form::password('password_confirmation',['class'=>'form-control form-control-sm','id'=>'confirmation_password','required'=>true,'placeholder'=>'Re-enter your new password ']) }}
                    </div>
                </div>
            <!-- Modal footer -->
            <div class="modal-footer" >
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success" >Update</button>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
<div class="sidenav-backdrop backdrop"></div>
<div class="preloader-backdrop">
    <div class="page-preloader">Loading</div>
</div>
<script src="{{mix('js/manifest.js')}}" ></script>
<script src="{{mix('js/vendor.js')}}" ></script>
<script src="{{mix('js/admin.js')}}"></script>
@yield('scripts')
</body>

</html>

resources/views/admin/partials/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <title> @yield('title') </title>
    <!-- GLOBAL MAINLY STYLES-->
    <link href="{{mix('css/admin.css')}}" rel="stylesheet">
    <!-- PAGE LEVEL STYLES-->
    @yield('styles')
</head>

resources/views/admin/partials/notify.blade.php
@if($message = Session::get('error'))
    <div class="alert alert-danger alert-block" style = "border-left: 2px solid rosybrown";>
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif
@if($message = Session::get('success'))
    <div class="alert alert-success alert-block" style = 'border-left: 2px solid #1c7430;'>
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif
@if($message = Session::get('info'))
    <div class="alert alert-info alert-block" style = 'border-left: 2px solid dodgerblue;'>
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif
@if($message = Session::get('warning'))
    <div class="alert alert-warning alert-block" style = 'border-left: 2px solid yellow;'>
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

resources/views/admin/partials/sidebar.blade.php
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div>
                @if(isset(request()->user()->userInfo['image']) && !empty(request()->user()->userInfo['image']))
                    <img src="{{asset('uploads/user/'.request()->user()->userInfo['image'])}}" width="45px" class="img-circle"/>
                @else
                    <img src="{{asset('img/default_user.jpg')}}"  width="45px" />
                @endif
            </div>
            <div class="admin-info">
                <div class="font-strong">{{auth()->user()->name}}</div><small>{{ucfirst(auth()->user()->role)}}</small></div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="{{route(request()->user()->role)}}"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>
            <li class="heading">FEATURES</li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-images"></i>
                    <span class="nav-label">Banner Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('banner.create') }}">Add Banner</a>
                    </li>
                    <li>
                        <a href="{{ route('banner.index') }}">List Banner</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-bold"></i>
                    <span class="nav-label">Brand Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('brand.create') }}">Add Brand</a>
                    </li>
                    <li>
                        <a href="{{ route('brand.index') }}">List Brand</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-sitemap"></i>
                    <span class="nav-label">Category Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('category.create') }}">Add Category</a>
                    </li>
                    <li>
                        <a href="{{ route('category.index') }}">List Category</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-shopping-bag"></i>
                    <span class="nav-label">Product Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('product.create') }}">Add Product</a>
                    </li>
                    <li>
                        <a href="{{ route('product.index') }}">List Product</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-shopping-basket"></i>
                    <span class="nav-label">Collection Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('collection.create') }}">Add Collection</a>
                    </li>
                    <li>
                        <a href="{{ route('collection.index') }}">List Collection</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-box-open"></i>
                    <span class="nav-label">Offers Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('offer.create') }}">Add Offers</a>
                    </li>
                    <li>
                        <a href="{{ route('offer.index') }}">List Offers</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-users"></i>
                    <span class="nav-label">User Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('user.create') }}">Add User</a>
                    </li>
                    <li>
                        <a href="{{ route('user.index') }}">List All User</a>
                    </li>
                    <li>
                        <a href="{{ route('user.show','customer') }}">List Customer</a>
                    </li>
                    <li>
                        <a href="{{ route('user.show','seller') }}">List Seller</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-shopping-cart"></i>
                    <span class="nav-label">Order Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="cards.html">Add Order</a>
                    </li>
                    <li>
                        <a href="cards.html">List Order</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-comments"></i>
                    <span class="nav-label">Review Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="cards.html">Add Review</a>
                    </li>
                    <li>
                        <a href="cards.html">List Review</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-file"></i>
                    <span class="nav-label">Pages Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('page.create') }}">Add Pages</a>
                    </li>
                    <li>
                        <a href="{{ route('page.index') }}">List Pages</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-file"></i>
                    <span class="nav-label">Blogs Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('blog.create') }}">Add blog</a>
                    </li>
                    <li>
                        <a href="{{ route('blog.index') }}">List blog</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-cogs"></i>
                    <span class="nav-label">Miscellaneous Setting</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="cards.html">Add Review</a>
                    </li>
                    <li>
                        <a href="cards.html">List Review</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="sidebar-item-icon fa fa-motorcycle"></i>
                    <span class="nav-label">Delivery Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="cards.html">Add Delivery Options</a>
                    </li>
                    <li>
                        <a href="cards.html">List Delivery Options</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

resources/views/admin/partials/topbar.blade.php
<header class="header">
    <div class="page-brand">
        <a class="link" href="{{route(request()->user()->role)}}">
            <span class="brand">Ecommerce
                <span class="brand-tip">CMS</span>
            </span>
            <span class="brand-mini">AC</span>
        </a>
    </div>
    <div class="flexbox flex-1">
        <!-- START TOP-LEFT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li>
                <a class="nav-link sidebar-toggler js-sidebar-toggler"><i class="ti-menu"></i></a>
            </li>
        </ul>
        <!-- END TOP-LEFT TOOLBAR-->
        <!-- START TOP-RIGHT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li class="dropdown dropdown-inbox">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>
                    <span class="badge badge-primary envelope-badge">0</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-menu-media">
                    <li class="dropdown-menu-header">
                        <div>
                            <span><strong>9 New</strong> Orders</span>
                            <a class="pull-right" href="mailbox.html">view all</a>
                        </div>
                    </li>
                    <li class="list-group list-group-divider scroller" data-height="240px" data-color="#71808f">
                        <div>
                            <a class="list-group-item">
                                <div class="media">
                                    <div class="media-img">
                                        <!-- <img src="./assets/img/users/u1.jpg" /> -->
                                    </div>
                                    <div class="media-body">
                                        <div class="font-strong"> </div>Jeanne Gonzalez<small class="text-muted float-right">Just now</small>
                                        <div class="font-13">Your proposal interested me.</div>
                                    </div>
                                </div>
                            </a>

                        </div>
                    </li>
                </ul>
            </li>
            <li class="dropdown dropdown-user">
                <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
                    @if(isset(request()->user()->userInfo['image']) && !empty(request()->user()->userInfo['image']))
                        <img src="{{asset('uploads/user/'.request()->user()->userInfo['image'])}}"  class="img-circle"/>
                    @else
                        <img src="{{asset('img/default_user.jpg')}}" class="img-circle"/>
                    @endif
                    <span>{{auth()->user()->name}}</span><i class="fa fa-angle-down m-l-5"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item edit-profile" href="javascript:;"><i class="fa fa-user"></i>Profile</a>
                    <a class="dropdown-item update-password" href="javascript:;"><i class="fa fa-key"></i>Change Password</a>
                    <li class="dropdown-divider"></li>
                    <a class="dropdown-item" href="{{route('logout')}}" onclick="event.preventDefault();document.getElementById('logoutForm').submit()">
                        {{ Form::open( ['url'=> route('logout'),'id'=>'logoutForm']) }}
                        {{ Form::close() }}
                    <i class="fa fa-power-off"></i>Logout</a>
                </ul>
            </li>
        </ul>
        <!-- END TOP-RIGHT TOOLBAR-->
    </div>
</header>