routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.home')->name('landing');
});
Route::group(['namespace'=>'\App\Http\Controllers'],function (){
    Route::get('/', 'FrontendController@homePage')->name('landing');
    Route::get('products','FrontendController@listAllProducts')->name('all-products');
    Route::get('products/{slug}','FrontendController@getProductDetail')->name('product-detail');
    Route::get('collections/{slug}','FrontendController@getCollectionDetail')->name('collection-detail');
    Route::get('pages/{slug}','FrontendController@getPageDetail')->name('page-detail');
    Route::get('blog','FrontendController@getAllBlog')->name('all-blogs');
    Route::get('blog/{slug}','FrontendController@blogDetail')->name('blog-detail');
    Route::get('page/contact-us','FrontendController@getContactUs')->name('contact');
    Route::get('search','FrontendController@searchResult')->name('search');
    Route::get('category','FrontendController@listAllProducts');
    Route::get('category/{slug}','FrontendController@getProductFromCategory')->name('cat-products');
    Route::get('category/{parent_slug}/{slug}','FrontendController@getProductFromSubCategory')->name('sub-cat-products');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=> '/admin','middleware'=> ['auth','admin'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('banner','BannerController')->except('show');
    Route::get('/banner/status-change/{id}/{status}','BannerController@changeStatus')->name('banner-change-status');
    Route::resource('category','CategoryController');
    Route::get('/category/status-change/{id}/{status}','CategoryController@changeStatus')->name('category-change-status');
    Route::resource('brand','BrandController')->except('show');
    Route::get('/brand/status-change/{id}/{status}','BrandController@changeStatus')->name('brand-change-status');
    Route::resource('product','ProductController');
    Route::get('/product/status-change/{id}/{status}','ProductController@changeStatus')->name('product-change-status');
    Route::resource('collection','ProductCollectionController');
    Route::get('/collection/status-change/{id}/{status}','ProductCollectionController@changeStatus')->name('collection-change-status');
    Route::resource('offer','OfferProductCollectionController');
    Route::get('/offer/status-change/{id}/{status}','OfferProductCollectionController@changeStatus')->name('offer-change-status');
    Route::resource('user','UserController');
    Route::get('/user/status-change/{id}/{status}','UserController@changeStatus')->name('user-change-status');
    Route::get('/user/{id}/change-password','UserController@showPasswordChangeForm')->name('change-pwd');
    Route::patch('/user/{id}/change-password','UserController@updatePassword')->name('user-update-password');
    Route::resource('page','PageController')->except(['show','store','delete']);
    Route::get('/page/status-change/{id}/{status}','PageController@changeStatus')->name('page-change-status');
    Route::resource('blog','BlogController');
    Route::get('/blog/status-change/{id}/{status}','BlogController@changeStatus')->name('blog-change-status');
});
Route::group(['prefix'=> '/customer','middleware'=> ['auth','customer'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@customer')->name('customer');

});
Route::group(['prefix'=> '/seller','middleware'=> ['auth','seller'],'namespace' => '\App\Http\Controllers'], function (){
    Route::get('/','HomeController@seller')->name('seller');
    Route::get('/product','ProductController@getProductBySeller')->name('seller.product');
    Route::get('/product/create','ProductController@showSellerProductForm')->name('seller.product.create');
    Route::get('/product/{id}','ProductController@getProductEditForm')->name('seller.product.edit');
    Route::post('/product','ProductController@storeProduct')->name('seller.product.store');
    Route::patch('/product/{id}','ProductController@updateProduct')->name('seller.product.update');
    Route::delete('/product/{id}/destroy','ProductController@deleteProduct')->name('seller.product.destroy');
    Route::get('/collection','ProductCollectionController@getCollectionBySeller')->name('seller.collection');
    Route::get('/collection/create','ProductCollectionController@showSellerCollectionForm')->name('seller.collection.create');
    Route::get('/collection/{id}','ProductCollectionController@getCollectionEditForm')->name('seller.collection.edit');
    Route::post('/collection','ProductCollectionController@storeCollection')->name('seller.collection.store');
    Route::patch('/collection/{id}','ProductCollectionController@updateCollection')->name('seller.collection.update');
    Route::delete('/collection/{id}/destroy','ProductCollectionController@deleteCollection')->name('seller.collection.destroy');
});
Route::patch('/update-me',[App\Http\Controllers\HomeController::class,'updateMe'])->name('update-me')->middleware('auth');
Route::post('/category/sub-cat',[App\Http\Controllers\CategoryController::class,'getAllSubCats'])->name('get-sub-cats')->middleware('auth');
Route::patch('/update-password',[App\Http\Controllers\HomeController::class,'updatePassword'])->name('update-password')->middleware('auth');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','status','role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function userInfo(){
        return $this->hasOne('\App\Models\UserInfo','user_id','id');
    }
    public  function getUpdateRule(){
        return [
            'name' => 'required|string|max:50',
            'address' => 'nullable|string|max:100',
            'phone' => 'nullable|string|max:20',
            'image' => 'sometimes|image|max:5000',
            'status' => 'sometimes|in:active,suspend'
        ];
    }
    public function getUpdatePassword(){
        return [
            'current_password' => ['required','string','min:8'],
            'password' => ['required','string','min:8','confirmed']
        ];
    }
    public  function getUserByRole($role){
        return $this->where('role',$role)->orderBy('name','ASC')->get();
    }
    public function getAllUsers(){
        return $this->where('id','!=',request()->user()->id)->orderBy('id','DESC')->get();
    }
    public function getRules(){
        return [
            'name' => 'required|string|max:50',
            'email' =>'required|email|unique:users,email',
            'password' => ['required','string','min:8','confirmed'],
//            'user_id'=>'required|exists:users,id',
            'phone' => 'required|string|max:20',
            'address' => 'required|string|max:100',
            'role' => 'required|in:customer,seller',
            'status' => 'required|in:active,suspend',
            'image' => 'required|image|max:5000'
        ];
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\UserInfo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $user,$userInfo;
    public function __construct(User $user,UserInfo $userInfo)
    {
        $this->user = $user;
        $this->userInfo = $userInfo;
    }
    private function validateId($id){
        $this->user = $this->user->find($id);
        if(!$this->user){
            request()->session()->flash('error','Sorry!, user does not exists');
            return  redirect()-route('user.index');
        }
    }
    public function index()
    {
        $all_users = $this->user->getAllUsers();
        return view('admin.user.index')
        ->with('is_all',true)
        ->with('all_users',$all_users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate($this->user->getRules());
//        dd($request->all());
        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        $this->user->fill($data);
        $status = $this->user->save($data);
        if($status){
            $data['user_id'] = $this->user->id;
            if($request->image){
                $image_name = imageUpload($request->image,'user',env('UserImageSize','200x200'));
                if($image_name){
                    $data['image'] = $image_name;
                }
            }
            $this->userInfo->fill($data);
            $this->userInfo->save();
            $request->session()->flash('success','User Created successfully.');
        }else{
            $request->session()->flash('error','Sorry!, error while creating user');

        }
//         dd($this->user);
        return redirect()->route('user.show',$this->user->role);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($role)
    {
        $roles = ['customer','seller'];
        if(!in_array($role,$roles)){
            abort(404);
        }
        $all_users = $this->user->getUserByRole($role);
        return view('admin.user.index')
        ->with('role',$role)
        ->with('all_users',$all_users);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->validateId($id);
        return view('admin.user.form')->with('user_detail',$this->user);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validateId($id);
        $request->validate($this->user->getUpdateRule());
        $data = $request->all();
        $this->user->fill($data);
        $status = $this->user->save();
        if($status){
            if($request->image){
                $image_name = imageUpload($request->image,'user',env('UserImageSize','200x200'));
                if($image_name){
                    if (isset($this->user->userInfo->image) && $this->user->userInfo->image != null) {
                        deleteImage($this->user->userInfo->image,'user');
                    }
                    $data['image'] = $image_name;
                }
            }
            if($this->user->userInfo == null){
                $data['user_id'] = $this->user->id;
                $this->user->userInfo = new UserInfo();
            }
            // dd($this->user->userInfo);
            $this->user->userInfo->fill($data);
            $this->user->userInfo->save();
            $request->session()->flash('success','User updated successfully.');
        }else{
            $request->session()->flash('error','Sorry!, error while updating user');

        }
        return redirect()->route('user.show',$this->user->role);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->validateId($id);
        $image = $this->userInfo->image;
        $status = $this->user->delete();
        if($status){
            if($image != null){
                deleteImage($image->image, 'user');
            }
            request()->session()->flash('success','user successfully deleted');
        }else{
            request()->session()->flash('error','Sorry!, user does not exists');
        }
        return redirect()->back();
    }

    public function changeStatus(Request $request){
        $this->validateId($request->id);
        if($this->user->status == 'active') {
            $this->user->status = 'suspend';
        }else{
            $this->user->status = 'active';
        }
        $status = $this->user->save();
        if($status){
            $request->session()->flash('success','user status changed successfully.');
        }else{
            $request->session()->flash('error','Sorry!, error while changing user status');
        }
            return redirect()->back();
    }

    public function showPasswordChangeForm($id){
        $this->validateId($id);
        return view('admin.user.password-change')->with('user_data',$this->user);
    }

    public function updatePassword(Request $request,$id){
        $this->validateId($id);
        $request->validate(
            ['password'=>'required|confirmed|string|min:8']
        );
//        dd($request->all());
        $this->user->password = Hash::make($request->passowrd);
        $status = $this->user->save();
        if($status){
            $request->session()->flash('success','user password updated successfully.');
        }else{
            $request->session()->flash('error','Sorry!, error while updating user password');
        }
        return redirect()->route('user.show',$this->user->role);
    }
}

resources/views/admin/user/form.blade.php
@extends('layouts.admin')
@section('title','User Form || Ecommerce Website')
@section('main_content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">User Form </div>
                    <a href="{{ route('user.index') }}" title="List All User" class="btn btn-info btn-sm btn-circle"><i class="fa fa-eye"></i></a>
                </div>
                <div class="ibox-body">
                    @if(isset($user_detail))
                        {{ Form::open(['url'=>route('user.update',$user_detail->id) ,'class'=>'form','files'=>true]) }}
                        @method('patch')
                    @else
                        {{ Form::open(['url'=>route('user.store') ,'class'=>'form','files'=>true]) }}
                    @endif
                        <div class="form-group row">
                            {{ Form::label('name','Name',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::text('name',@$user_detail->name,['class'=>'form-control form-control-sm','id'=>'name','required'=>true,'placeholder'=>'Enter your name']) }}
                                @error('name')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        @if(!isset($user_detail))
                        <div class="form-group row">
                            {{ Form::label('email','Email Address',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::text('email',@$user_detail->email,['class'=>'form-control form-control-sm','id'=>'email','required'=>true,'placeholder'=>'Enter user email address']) }}
                                @error('email')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('password','Password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::password('password',['class'=>'form-control form-control-sm','id'=>'password','required'=>true,'placeholder'=>'Enter  password']) }}
                                @error('password')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('confirmation_password','Re-password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::password('password_confirmation',['class'=>'form-control form-control-sm','id'=>'confirmation_password','required'=>true,'placeholder'=>'Re-enter  password ']) }}
                                @error('confirmation_password')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        @endif
                        <div class="form-group row">
                            {{ Form::label('phone','Phone',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::tel('phone',@$user_detail->userInfo->phone,['class'=>'form-control form-control-sm','id'=>'phone','required'=>false,'placeholder'=>'Enter your phone number']) }}
                                @error('phone')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    <div class="form-group row">
                        {{ Form::label('address','Address',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                        <div class="col-sm-12 col-md-7">
                            {{ Form::text('address',@$user_detail->userInfo->address,['class'=>'form-control form-control-sm','id'=>'address','required'=>false,'placeholder'=>'Enter your address']) }}
                            @error('address')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                        <div class="form-group row">
                            {{ Form::label('role','Role',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::select('role',['customer'=>"Customer",'seller'=>"Seller"],@$user_detail->role,['class'=>'form-control form-control-sm','id'=>'role','required'=>true]) }}
                                @error('role')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('status','Status',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::select('status',['active'=>"Active",'suspend'=>"Inactive"],@$user_detail->status,['class'=>'form-control form-control-sm','id'=>'status','required'=>true]) }}
                                @error('status')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    <div class="form-group row">
                        {{ Form::label('image_update','Image',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                        <div class="col-sm-12 col-md-4">
                            {{ Form::file('image',['id'=>'image_update','required'=>(isset($user_detail) ? false : true),'accept'=>"image/*",'onchange'=>"readURL(this,'thumb')"]) }}
                            @error('image')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col-md-3">
                            @if(isset($user_detail) && !empty($user_detail->userInfo->image))
                                <img src="{{ asset("uploads/user/".$user_detail->userInfo->image) }}" alt="" id="thumb" class="img-fluid img-thumbnail">
                            @else
                                <img src="" alt="" id="thumb" class="img-fluid img-thumbnail">
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12 col-md-7 offset-md-5">
                            <button type="submit" class="btn btn-success btn-block btn-sm" >Submit</button>
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('title','User List || Ecommerce Website')
@section('main_content')
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">All {{ isset($is_all) ? '' : ucfirst($role) }} User List</div>
                        <a href="{{ route('user.create') }}" title="Add User" class="btn btn-success btn-circle"><i class="fa fa-plus"></i></a>
                    </div>
                    <div class="ibox-body">
                        <table class="table table-striped table-hover data-table">
                            <thead class="thead-dark">
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            @if(isset($is_all))
                            <th>Role</th>
                            @endif
                                <th>Image</th>
                                <th>Status</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                            @if($all_users->count())
                                @foreach($all_users as $data)
                                <tr>
                                    <td>{{$data->name}}</td>
                                    <td>{{$data->email}}</td>
                                    <td>{{ @$data->userInfo->phone }}</td>
                            @if(isset($is_all))
                                    <td>
                                        {{ $data->role }}
                                    </td>
                                @endif
                                    <td>
                                    @if($data->userInfo)
                                        <a href="{{ asset('uploads/user/'.$data->userInfo->image) }}" data-lightbox = "image-{{ $data->id }}" data-title = {{ $data->title }}>Preview</a>
                                    @endif
                                    </td>
                                    <td>
                                        <a href="{{ route('user-change-status',[$data->id,$data->status]) }}" class="badge badge-{{ $data->status == 'active' ? 'success' : 'danger' }}">{{ $data->status == 'active' ? 'Active' : 'Inactive' }}</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('change-pwd',$data->id) }}" title="Update Password" class="btn btn-secondary btn-sm btn-circle">
                                            <i class="fa fa-key"></i>
                                        </a>
                                        <a href="{{ route('user.edit',$data->id) }}" title="Edit this user" class="btn btn-primary btn-sm btn-circle">
                                            <i class="fa fa-pen"></i>
                                        </a>
                                        <a href="javascript:;" title="Delete this user" class="btn btn-warning btn-sm btn-circle btn-delete">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                        {{ Form::open(['url' => route('user.destroy',$data->id) , 'class' => 'delete-form' ]) }}
                                            @method('delete')
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/user/password-change.blade.php
@extends('layouts.admin')
@section('title','User Password Change Form || Ecommerce Website')
@section('main_content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">User Password Change Form </div>
                </div>
                <div class="ibox-body">
                    {{ Form::open(['url'=>route('user-update-password',$user_data->id) ,'class'=>'form']) }}
                        @method('patch')
                        <div class="form-group row">
                            {{ Form::label('password','New Password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::password('password',['class'=>'form-control form-control-sm','id'=>'password','required'=>true,'placeholder'=>'Enter  password']) }}
                                @error('password')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('confirmation_password','Re-type New password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::password('password_confirmation',['class'=>'form-control form-control-sm','id'=>'confirmation_password','required'=>true,'placeholder'=>'Re-enter  password ']) }}
                                @error('confirmation_password')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-md-7 offset-md-5">
                                <button type="submit" class="btn btn-success btn-block btn-sm" >Update Password</button>
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection